name: django-project-template

x-django-project: &django-project-base
  build:
    context: ..
    dockerfile: docker/django-development.Dockerfile
  volumes:
  - ..:/project
  environment:  
  - DEBUG=True
  - SECRET_KEY=django-insecure-@zjjw+uk*3v8ok9)4d^^_t^2)4zzta5k%i(hta=kq_pu0n)%*w
  - DJANGO_LOGLEVEL=INFO
  - POSTGRES_HOST=postgres
  - POSTGRES_PORT=5432
  - POSTGRES_NAME=postgres
  - POSTGRES_USER=postgres
  - PGPASSWORD=postgres
  - PGOPTIONS=-c search_path=public
  - ALLOWED_HOSTS=localhost,127.0.0.1,[::1]
  - CORS_ALLOWED_ORIGINS=http://localhost:8000,http://localhost:4200
  - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://localhost:4200
  - CACHE_BACKEND=django.core.cache.backends.locmem.LocMemCache
  - CACHE_LOCATION=unique-snowflake
  - DEFAULT_FILE_STORAGE=django.core.files.storage.FileSystemStorage
  - STATICFILES_STORAGE=django.contrib.staticfiles.storage.StaticFilesStorage
  - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
  - EMAIL_USE_TLS=False
  - EMAIL_HOST=mailhog
  - EMAIL_PORT=1025
  - EMAIL_SUBJECT_PREFIX=[DJANGO_PROJECT]
  - DJANGO_ADMINS=Admin Dev <admin@dev.com>

services:

  django:
    <<: *django-project-base
    # entrypoint: /project/bin/entrypoint-django.development.sh
    command: ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
    - "8000:8000"
    depends_on:
    - postgres
    - redis
    - mailhog
    # - celery
    # - celery-beat

  postgres:
    image: postgres:15-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6.2.6-alpine
    volumes:
    - redis_data:/var/lib/redis/data
    expose:
    - 6379

  # celery:
  #   <<: *django-project-base
  #   entrypoint: /project/bin/entrypoint-celeryworker.sh

  # celery-beat:
  #   <<: *django-project-base
  #   entrypoint: /project/bin/entrypoint-celerybeat.sh

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none' # disable saving logs
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui

volumes:
  postgres_data:
    name: django-project-db-dev
  redis_data:
    name: django-project-redis-dev
